version: 2
jobs:
  build_and_test:
    working_directory: ~/venue-server
    docker:
    - image: 'python:3.6-alpine3.8'
      environment:
        POSTGRES_HOST: localhost
        REDIS_HOST: localhost
    - image: 'postgres:alpine'
      environment:
        POSTGRES_DB: venuepostgress
        POSTGRES_USER: venueadmin
        POSTGRES_PASSWORD: badpassword
    - image: 'bitnami/redis:latest'
      environment:
        REDIS_PASSWORD: badpassword
    steps:
    - setup_remote_docker
    - run:
        name: 'Install system dependencies'
        command: 'apk add --update --no-cache gcc build-base linux-headers postgresql-dev ncurses-dev git gettext libffi-dev libressl-dev'
    - checkout
    - restore_cache:
        keys:
        - 'venue-server-pip-{{ checksum "requirements.txt" }}'
        - 'venue-server-pip-'
    - run:
        name: 'Install python dependencies'
        command: |
          python3 -m venv venv
          . venv/bin/activate
          pip install --requirement requirements.txt
    - save_cache:
        key: 'venue-server-pip-{{ checksum "requirements.txt" }}'
        paths:
        - venv
    - run:
        name: 'Prepare django'
        command: |
          . venv/bin/activate
          python manage.py collectstatic --noinput
          python manage.py migrate
    - run:
        name: 'Run tests'
        command: |
          . venv/bin/activate
          pytest
  build_image:
    docker:
    - image: docker:17.09.0-ce
    steps:
    - setup_remote_docker
    - checkout
    - run:
        name: 'Tag image and push to server'
        command: |
          TAG=v0.1.$CIRCLE_BUILD_NUM
          docker pull volentixlabs/venueserver:latest
          docker build --cache-from=volentixlabs/venueserver:latest -t volentixlabs/venueserver:$TAG .
          echo $DOCKER_PASSWORD | docker login -u $DOCKER_USER --password-stdin
          docker tag volentixlabs/venueserver:$TAG volentixlabs/venueserver:latest
          docker push volentixlabs/venueserver
          echo $TAG
  deploy:
    docker:
    - image: 'volentixlabs/aws-kube-deploy:v0.1.2'
    working_directory: ~/repo
    steps:
    - checkout
    - run: 'kops export kubecfg'
    - run:
      name: 'Deploy'
      command: |
        TAG=v0.1.$CIRCLE_PREVIOUS_BUILD_NUM
        sed 's/IMAGE_VERSION/'$TAG'/' kube/dev.yml.template > kube/dev.yml
        kubectl apply -f kube/dev.yml
workflows:
  version: 2
  build_and_deploy:
    jobs:
    - build_and_test
    - build_image:
        requires:
        - build_and_test
        filters:
          branches:
            only: master
    - deploy:
        requires:
        - build_and_test
        - build_and_test
        filters:
          branches:
            only: master
